<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.kvarun701</groupId>
        <artifactId>etherflow-parent</artifactId>
        <version>0.1.1</version>
    </parent>
    <artifactId>etherflow-starter-webflux</artifactId>
    <packaging>pom</packaging>
    <name>EtherFlow :: Starter :: WebFlux</name>
    <description>Starter for building reactive web apps with EtherFlow</description>

    <dependencies>
        <dependency>
            <groupId>io.github.kvarun701</groupId>
            <artifactId>etherflow-streams</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.kvarun701</groupId>
            <artifactId>etherflow-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.kvarun701</groupId>
            <artifactId>etherflow-codec</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.kvarun701</groupId>
            <artifactId>etherflow-http</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.kvarun701</groupId>
            <artifactId>etherflow-web</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.kvarun701</groupId>
            <artifactId>etherflow-server-netty</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.kvarun701</groupId>
            <artifactId>etherflow-client</artifactId>
        </dependency>
    </dependencies>
</project>
